CREATE DATABASE south_database_new;

--创建杆塔数据表
--注：RELATION_TYPE导入时存在空缺，因此导入时是varchar
--后续改为numeric。LONGITUDE,LATITUDE同理
CREATE TABLE NET_MONITORPOSITION_B(
id SERIAL PRIMARY KEY,
BS_ID VARCHAR(50),
LINE_ID	VARCHAR(50),
LINE_NAME VARCHAR(50),
POLE_ID VARCHAR(50),
POLE_NAME VARCHAR(50),
COMPANY VARCHAR(50),
BUREAU VARCHAR(50),
VOLTAGE_LEVEL VARCHAR(50),
RELATION_TYPE VARCHAR(50),
LONGITUDE VARCHAR(50),
LATITUDE VARCHAR(50),
REMARKS VARCHAR(50),
MISID VARCHAR(50));

--导入数据
COPY NET_MONITORPOSITION_B(BS_ID, LINE_ID, LINE_NAME, POLE_ID, POLE_NAME, COMPANY, BUREAU, VOLTAGE_LEVEL, RELATION_TYPE, LONGITUDE, LATITUDE, REMARKS, MISID)
FROM '/mnt/usb/NewData/NET_MONITORPOSITION_B.csv'
DELIMITER ',' NULL 'NULL'
CSV HEADER;

--更新数据
UPDATE NET_MONITORPOSITION_B
SET 
    RELATION_TYPE = CASE WHEN RELATION_TYPE = '' THEN '-1' ELSE RELATION_TYPE END,
    LATITUDE = CASE WHEN LATITUDE = '' THEN '-1' ELSE LATITUDE END,
    LONGITUDE = CASE WHEN LONGITUDE = '' THEN '-1' ELSE LONGITUDE END;

--修改列的数据类型
ALTER TABLE NET_MONITORPOSITION_B
	ALTER COLUMN LONGITUDE TYPE numeric 
	USING COALESCE(LONGITUDE::numeric, -1)
	ALTER COLUMN LATITUDE TYPE numeric 
	USING COALESCE(LATITUDE::numeric, -1)
	ALTER COLUMN RELATION_TYPE TYPE numeric 
	USING COALESCE(RELATION_TYPE::numeric, -1);

--创建存放天气的表,结构提前查看csv确定,确保与csv的表头对应
CREATE TABLE RTM_WEATHER_D(
id SERIAL PRIMARY KEY,
REC_BS_ID VARCHAR(50),
REC_UPDATE_TIME TIMESTAMP,
REC_TEMPERATURE	VARCHAR(50), --后改为numeric，null值替换为-999
REC_HUMIDITY VARCHAR(50), --后改为numeric，null值替换为-999
REC_WIND_SPEED VARCHAR(50), --后改为numeric，null值替换为-999
REC_WIND_DIRECTION VARCHAR(50), --后改为numeric，null值替换为-999
REC_RAIN_AMOUNT VARCHAR(50), --后改为numeric，null值替换为-999
REC_ATM_PRESSURE VARCHAR(50), --后改为numeric，null值替换为-999
REC_SUNSHINE VARCHAR(50), --后改为numeric，null值替换为-999
REC_WINDSPEED_1MIN VARCHAR(50), --后改为numeric，null值替换为-999
REC_WINDSPEED_10MIN VARCHAR(50), --后改为numeric，null值替换为-999
REC_WIND_DIRECTION_1MIN VARCHAR(50), --后改为numeric，null值替换为-999
REC_WIND_DIRECTION_10MIN VARCHAR(50), --后改为numeric，null值替换为-999
REC_MAX_WINDSPEED VARCHAR(50), --后改为numeric，null值替换为-999
REC_CREATE_TIME DATE,
REC_SYNC NUMERIC);

--导入数据
COPY RTM_WEATHER_D(REC_BS_ID, REC_UPDATE_TIME, REC_TEMPERATURE, REC_HUMIDITY, REC_WIND_SPEED, REC_WIND_DIRECTION, REC_RAIN_AMOUNT, REC_ATM_PRESSURE, REC_SUNSHINE, REC_WINDSPEED_1MIN, REC_WINDSPEED_10MIN, REC_WIND_DIRECTION_1MIN, REC_WIND_DIRECTION_10MIN, REC_MAX_WINDSPEED, REC_CREATE_TIME, REC_SYNC)
FROM '/mnt/usb/NewData/RTM_WEATHER_D20-21.csv'
DELIMITER ',' NULL 'NULL'
CSV HEADER;

--导入表格缺失值替换为-999
UPDATE RTM_WEATHER_D
SET 
    REC_WIND_SPEED = CASE WHEN REC_WIND_SPEED = '' THEN '-999' ELSE REC_WIND_SPEED END,
    REC_WIND_DIRECTION = CASE WHEN REC_WIND_DIRECTION = '' THEN '-999' ELSE REC_WIND_DIRECTION END,
    REC_RAIN_AMOUNT = CASE WHEN REC_RAIN_AMOUNT = '' THEN '-999' ELSE REC_RAIN_AMOUNT END,
    REC_ATM_PRESSURE = CASE WHEN REC_ATM_PRESSURE = '' THEN '-999' ELSE REC_ATM_PRESSURE END,
    REC_SUNSHINE = CASE WHEN REC_SUNSHINE = '' THEN '-999' ELSE REC_SUNSHINE END,
    REC_WINDSPEED_1MIN = CASE WHEN REC_WINDSPEED_1MIN = '' THEN '-999' ELSE REC_WINDSPEED_1MIN END,
    REC_WINDSPEED_10MIN = CASE WHEN REC_WINDSPEED_10MIN = '' THEN '-999' ELSE REC_WINDSPEED_10MIN END,
    REC_WIND_DIRECTION_1MIN = CASE WHEN REC_WIND_DIRECTION_1MIN = '' THEN '-999' ELSE REC_WIND_DIRECTION_1MIN END,
    REC_WIND_DIRECTION_10MIN = CASE WHEN REC_WIND_DIRECTION_10MIN = '' THEN '-999' ELSE REC_WIND_DIRECTION_10MIN END,
    REC_MAX_WINDSPEED = CASE WHEN REC_MAX_WINDSPEED = '' THEN '-999' ELSE REC_MAX_WINDSPEED END;

--表格列的数据类型转换
ALTER TABLE RTM_WEATHER_D 
ALTER COLUMN REC_WIND_SPEED TYPE NUMERIC 
USING COALESCE(REC_WIND_SPEED::NUMERIC,-999),
ALTER COLUMN REC_WIND_DIRECTION TYPE NUMERIC 
USING COALESCE(REC_WIND_DIRECTION::NUMERIC,-999),
ALTER COLUMN REC_RAIN_AMOUNT TYPE NUMERIC 
USING COALESCE(REC_RAIN_AMOUNT::NUMERIC,-999),
ALTER COLUMN REC_ATM_PRESSURE TYPE NUMERIC 
USING COALESCE(REC_ATM_PRESSURE::NUMERIC,-999),
ALTER COLUMN REC_SUNSHINE TYPE NUMERIC 
USING COALESCE(REC_SUNSHINE::NUMERIC,-999),
ALTER COLUMN REC_WINDSPEED_1MIN TYPE NUMERIC 
USING COALESCE(REC_WINDSPEED_1MIN::NUMERIC,-999),
ALTER COLUMN REC_WINDSPEED_10MIN TYPE NUMERIC 
USING COALESCE(REC_WINDSPEED_10MIN::NUMERIC,-999),
ALTER COLUMN REC_WIND_DIRECTION_1MIN TYPE NUMERIC 
USING COALESCE(REC_WIND_DIRECTION_1MIN::NUMERIC,-999),
ALTER COLUMN REC_WIND_DIRECTION_10MIN TYPE NUMERIC 
USING COALESCE(REC_WIND_DIRECTION_10MIN::NUMERIC,-999),
ALTER COLUMN REC_MAX_WINDSPEED TYPE NUMERIC 
USING COALESCE(REC_MAX_WINDSPEED::NUMERIC,-999);

--创建覆冰数据表格
CREATE TABLE RTM_LEADBACKICE_D (
id SERIAL PRIMARY KEY,
REC_BS_ID VARCHAR(50),
REC_UPDATE_TIME TIMESTAMP,
REC_PHASE VARCHAR(50),
REC_ICE_HEIGHT VARCHAR(50),
REC_MAXPULL VARCHAR(50),
REC_MAXPULL_WIND VARCHAR(50),
REC_MAXPULL_OBLIQUE VARCHAR(50),
REC_ICE_WEIGHT VARCHAR(50),
REC_CREATE_TIME DATE,
REC_SYNC VARCHAR(50),
REC_ICE_SPEED	VARCHAR(50),
REC_REBUILD_ICE_HEIGHT VARCHAR(50));

--导入覆冰数据
COPY RTM_LEADBACKICE_D(REC_BS_ID, REC_UPDATE_TIME, REC_PHASE, REC_ICE_HEIGHT, REC_MAXPULL, REC_MAXPULL_WIND, REC_MAXPULL_OBLIQUE	, REC_ICE_WEIGHT, REC_CREATE_TIME, REC_SYNC, REC_ICE_SPEED, REC_REBUILD_ICE_HEIGHT)
FROM '/mnt/usb/NewData/RTM_LEADBACKICE_D20-21.csv'
DELIMITER ',' NULL 'NULL'
CSV HEADER;

--更新覆冰数据表数据
UPDATE RTM_LEADBACKICE_D
SET 
    REC_ICE_HEIGHT = CASE WHEN REC_ICE_HEIGHT = '' THEN '-999' ELSE REC_ICE_HEIGHT END,
    REC_MAXPULL = CASE WHEN REC_MAXPULL = '' THEN '-999' ELSE REC_MAXPULL END,
    REC_MAXPULL_WIND = CASE WHEN REC_MAXPULL_WIND = '' THEN '-999' ELSE REC_MAXPULL_WIND END,
    REC_MAXPULL_OBLIQUE = CASE WHEN REC_MAXPULL_OBLIQUE = '' THEN '-999' ELSE REC_MAXPULL_OBLIQUE END,
    REC_ICE_WEIGHT = CASE WHEN REC_ICE_WEIGHT = '' THEN '-999' ELSE REC_ICE_WEIGHT END,
    REC_SYNC = CASE WHEN REC_SYNC = '' THEN '-999' ELSE REC_SYNC END,
    REC_ICE_SPEED = CASE WHEN REC_ICE_SPEED = '' THEN '-999' ELSE REC_ICE_SPEED END,
    REC_REBUILD_ICE_HEIGHT = CASE WHEN REC_REBUILD_ICE_HEIGHT = '' THEN '-999' ELSE REC_REBUILD_ICE_HEIGHT END;

--修改表格列的数据类型
ALTER TABLE RTM_LEADBACKICE_D
ALTER COLUMN REC_ICE_HEIGHT TYPE NUMERIC 
USING COALESCE(REC_ICE_HEIGHT::NUMERIC,-999),
ALTER COLUMN REC_MAXPULL TYPE NUMERIC 
USING COALESCE(REC_MAXPULL::NUMERIC,-999),
ALTER COLUMN REC_MAXPULL_WIND TYPE NUMERIC 
USING COALESCE(REC_MAXPULL_WIND::NUMERIC,-999),
ALTER COLUMN REC_MAXPULL_OBLIQUE TYPE NUMERIC 
USING COALESCE(REC_MAXPULL_OBLIQUE::NUMERIC,-999),
ALTER COLUMN REC_ICE_WEIGHT TYPE NUMERIC 
USING COALESCE(REC_ICE_WEIGHT::NUMERIC,-999),
ALTER COLUMN REC_SYNC TYPE NUMERIC 
USING COALESCE(REC_SYNC::NUMERIC,-999),
ALTER COLUMN REC_ICE_SPEED TYPE NUMERIC 
USING COALESCE(REC_ICE_SPEED::NUMERIC,-999),
ALTER COLUMN REC_REBUILD_ICE_HEIGHT TYPE NUMERIC 
USING COALESCE(REC_REBUILD_ICE_HEIGHT::NUMERIC,-999);

--索引的建立
CREATE INDEX bs_id_and_time
    ON rtm_weather_d_n USING btree
    (rec_bs_id, rec_update_time);

CREATE INDEX bs_id_and_time_ice
    ON rtm_leadback_ice_n USING btree
    (rec_bs_id, rec_update_time);

--表间联系的建立
--建立weather表与杆塔信息表的联系,通过rec_bs_id联系
ALTER TABLE IF EXISTS rtm_weather_d_n
    ADD CONSTRAINT fk_rec_bs_id FOREIGN KEY (rec_bs_id)
    REFERENCES net_monitorposition_b (bs_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

--建立ice表与杆塔信息表的联系
ALTER TABLE IF EXISTS rtm_leadbackice_d_n
    ADD CONSTRAINT fk_rec_bs_id FOREIGN KEY (rec_bs_id)
    REFERENCES net_monitorposition_b (bs_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;